import { sql } from "kysely";
import type { Migration } from "./types.ts";

// Frozen word lists match the first readable personal-workspace suggestion.
// Only exact identifiers generated by the old implementation are changed.
// Workspace IDs, ownership, existing tokens, files and allowances are untouched.
export const CANONICAL_SQL = `
DO $body$
DECLARE
  adjectives text[] := ARRAY['amber','bright','calm','clear','coral','crisp','dawn','deep','gentle','golden','green','hidden','indigo','kind','little','lively','lunar','mellow','misty','noble','open','quiet','rapid','silver','soft','solar','still','sunny','tidal','vivid','warm','wild'];
  nouns text[] := ARRAY['atlas','bay','birch','bloom','brook','cedar','cove','dune','elm','fern','field','forest','garden','grove','harbor','hill','island','lake','maple','meadow','moon','oak','ocean','orchard','pine','pond','reef','river','shore','sky','stone','willow'];
  item record;
  digest bytea;
  base_slug text;
  candidate text;
  display_name text;
  suffix integer;
BEGIN
  FOR item IN
    SELECT o.id,o.name,p.user_id FROM auth.organization o
    JOIN relay.personal_workspaces p ON p.organization_id=o.id
    WHERE o.slug='personal-' || substr(encode(sha256(convert_to('relay-personal-workspace:' || p.user_id,'UTF8')),'hex'),1,32)
    ORDER BY o.id FOR UPDATE OF o
  LOOP
    digest := sha256(convert_to('relay-personal-workspace:' || item.user_id,'UTF8'));
    base_slug := adjectives[1 + get_byte(digest,0) % 32] || '-' || nouns[1 + get_byte(digest,1) % 32] || '-' || (1000 + (get_byte(digest,2)*256 + get_byte(digest,3)) % 9000)::text;
    display_name := initcap(adjectives[1 + get_byte(digest,0) % 32] || ' ' || nouns[1 + get_byte(digest,1) % 32]);
    candidate := base_slug;
    suffix := 1;
    WHILE EXISTS(SELECT 1 FROM auth.organization WHERE slug=candidate AND id<>item.id) LOOP
      suffix := suffix + 1;
      candidate := base_slug || '-' || suffix::text;
    END LOOP;
    UPDATE auth.organization SET slug=candidate,name=CASE WHEN name='Personal' THEN display_name ELSE name END WHERE id=item.id;
    INSERT INTO relay.audit_events(actor_type,action,target_type,target_id,outcome)
    VALUES('system','workspace.readable_identifier','workspace',item.id,'success');
  END LOOP;
END;
$body$;
`;

export const migration: Migration = {
  id: "0007_workspace_names",
  checksumSha256:
    "a026b70767286c460aa716d7a05ef48ba63e1543e205ed8529b9c7a0ad43d6b1",
  transactional: true,
  up: async (db) => {
    await sql.raw(CANONICAL_SQL).execute(db);
  },
};
